### ISSUE TITLE
Add a runnable to delete a PR

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#111]

**Comment by bastienterrier** [comment]
To "delete" a PR, just call the `UpdatePullRequestRunnable` as follow:
```
    onError:
      - callback: UpdatePullRequestRunnable
        args:
          state: close
```
