### ISSUE TITLE
Make `DeleteFileRunnable` works with an optional or string `files` arg

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#116]
In order to pipe `CheckAddedFilesRule` with `DeleteFileRunnable`, it's necessary to make the Post-Actions working with: 

- [x] a string argument.
E.g. :
```yaml
  - name: checkAddedFiles
    options:
      regexp: '.*\.exe$'
    onSuccess: 
      - callback: DeleteFilesRunnable
        args:
          files: '{{#data.addedFiles}}{{.}}{{/data.addedFiles}}'
```

- [x] a files argument: will take all data returned by the CheckAddedFiles (or later CheckRemoved/CheckUpdated)
