### ISSUE TITLE
Add a 'branch' option in CommitMessageRule

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#121]
Add this option to check the regexp only if the PUSH event concern the 'branch'

**Comment by bastienterrier** [comment]
```yaml
...
options:
  regexp: '...'
  branches:
    only:
      - master
      - develop
    ignore:
      - gh-pages
```
