### ISSUE TITLE
Add a Runnable to create a Tag

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#122]

**Comment by bastienterrier** [comment]
@EmmanuelDemey do you have any use-case ?

**Comment by EmmanuelDemey** [comment]
Automatically create a tag when we merge something on the principal branch. Based in the pr title ?
For example a PR named "3.0.0" will automatically create a tag 3.0.0

**Comment by bastienterrier** [comment]
```yaml
  - name: commitMessage
    options:
      regexp: '#(v.*)#'
    onSuccess:
      - callback : CreateTagRunnable
        args:
          tag: '{{data.commits.0.matches.1}}'
          message: 'new version !'
```
