### ISSUE TITLE
Rules add user options

### ISSUE THREAD

**Issue by bastienterrier** [DX-DeveloperExperience/hygie#205]
```yaml
- name: issueComment
    options:
      regexp: '.*'
      users:
         ignore:
           - bastienterrier
         only:
           - bastienterrier
```
