### ISSUE TITLE
commitMessage rule - specify a branch

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/hygie#213]
When we want to create a tag automatically, based on the commit message, are we able to filter the git branch ? Only create the tag, when the commit has been merge on a specific branch ? 

```yaml
 - name: commitMessage
    options:
      regexp: '#(v.*)#'
    onSuccess:
      - callback : CreateTagRunnable
        args:
          tag: '{{data.commits.0.matches.1}}'
```

More generally, are we able to use the default branch of the git repository in our rulesrc file ? Maybe via a placeholder name `default_branch` that will be evaluated automatically by the code.
